name: 'secrets-to-dotenv2'
description: 'Utility action that exports all github secrets environment variables and write to file.'
author: 'mravselj'
inputs:
  secrets:
    required: true
    description: JSON representation of the secrets, use provided placeholder'
  file:
    required: false
    description: 'File to export secrets to, e.g.: .env, If not provided, will export to .env. If empty, will not export to file'
    default: '.env'
  no_env:
    required: false
    description: 'Do not export secrets to environment variables'
  prefix:
    required: false
    description: 'Prefix to add to all secrets, e.g.: SECRET_'
  include:
    required: false
    description: 'Comma-separated list of secrets to export'
  exclude:
    required: false
    description: 'Comma-separated list of secrets to skip exporting'
  convert:
    required: false
    description: 'Converts secrets name to a specific string format'
  convert_prefix:
    required: false
    description: 'Include prefix (or not) on conversion. True by default'
  remove_prefix:
    required: false
    description: 'Removes specified prefix from all variables. Useful for DEV_ STG_, PROD_ prefixes. Empty by default'  
  override:
    required: false
    description: 'Override existing environment variables'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: command
  color: blue
